server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息中间件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost #rabbitMQ服务地址
                port: 5672 #rabbitMQ服务端口
                username: guest #rabbitMQ服务账号
                password: guest #rabbitMQ服务密码
      bindings: #服务的整合配置
        output: #表示这是输出，即消息提供者
          destination: studyExchange #定义Exchange名称
          content-type: application/json #定义消息的类型
          binder: defaultRabbit #声明需要绑定的具体消息设置

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳间隔时间（默认30秒）
    lease-expiration-duration-in-seconds: 5 #设置节点注销时间，默认（90秒）
    instance-id: send-8801.com #设置在消息列表服务的显示名称
    prefer-ip-address: true #访问路径由服务名指定为IP
