server:
  port: 8006
  servlet:
    context-path: /cloud-providerconsul-service

spring:
  application:
    name: cloud-providerconsul-service
  cloud:
    consul:
      host: 192.168.13.161
      port: 8500
      discovery:
        service-name: ${spring.application.name}