server:
  port: 8001
  servlet:
    context-path: /cloud-provider-service

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.13.161:3306/springcloudDb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.infocore.springcloud.entites #设置mybatis映射的实体类路径

# eureka client 配置
eureka:
  client:
    # 表示自己是否注册到eureka server，默认为true
    register-with-eureka: true
    # 是否从eureka server抓取到已有的注册信息，默认为true。单节点环境无所谓，集群环境必须配置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
  instance:
    instance-id: payment8001 #application中对外显示的状态名称
    prefer-ip-address: true #显示上面状态名称的ip