server:
  port: 80
  servlet:
    context-path: /cloud-consumer-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版

spring:
  application:
    name: cloud-consumer-service

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

#开启openfeign日志功能
logging:
  level:
    #openfeign日志以什么日志级别监控那个接口
    cn.infocore.springcloud.service.PaymentOpenfeignService: debug