server:
  port: 8004
  servlet:
    context-path: /cloud-provider-service

spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-service
  # zookeeper配置
  cloud:
    zookeeper:
      connect-string: 192.168.13.161:2181