server:
  port: 83

spring:
  application:
    name: cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848
        server-addr: 192.168.13.169:8848

service-url:
  nacos-user-service: http://cloud-nacos-provider